spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: brayanwtff@gmail.com
    password: fuew evbl olbe hrxx
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:3307/teacherhub
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

application:
  jwt:
    SECRET_KEY: FC120BB229E9EC3D04138A46DD1A65FB32EB3A13BDDF90CE88BA62230602BFEC



